WellCommerce\Bundle\ThemeBundle\Entity\Theme:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: theme
    repositoryClass: WellCommerce\Bundle\ThemeBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: false
            nullable: false
        folder:
            type: string
            length: 255
            unique: true
            nullable: false
