well_commerce_theme:
    configuration:
        theme:
            orm:
                factory: WellCommerce\Bundle\ThemeBundle\Factory\ThemeFactory
                repository: WellCommerce\Bundle\ThemeBundle\Repository\ThemeRepository
                mapping: "@WellCommerceThemeBundle/Resources/config/doctrine/Theme.orm.yml"
                entity: WellCommerce\Bundle\ThemeBundle\Entity\Theme
        theme_css:
            orm:
                mapping: "@WellCommerceThemeBundle/Resources/config/doctrine/ThemeCss.orm.yml"
                entity: WellCommerce\Bundle\ThemeBundle\Entity\ThemeCss

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ThemeBundle\Entity\ThemeInterface: WellCommerce\Bundle\ThemeBundle\Entity\Theme
