# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ThemeBundle\Entity\ThemeInterface: WellCommerce\Bundle\ThemeBundle\Entity\Theme

well_commerce_api:
    request_handler:
        theme:
            manager: theme.manager
    serialization:
        WellCommerce\Bundle\ThemeBundle\Entity\Theme:
            mapping: "@WellCommerceThemeBundle/Resources/config/serialization/Theme.yml"
