WellCommerce\Bundle\ThemeBundle\Entity\Theme:
    fields:
        id:
            groups:
                - default
                - theme
        name:
            groups:
                - default
                - theme
        folder:
            groups:
                - default
                - theme
    associations: {}
